AWSTemplateFormatVersion: 2010-09-09
      
Resources:
  EC2ApacheInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a23ccb2cdd9286bb
      InstanceType: t2.micro
      SubnetId: subnet-00a51f0a43d984635
      Tags:
      - Key: Name
        Value: My Apache Server
      
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/sh
            sudo su 
            yum update -y
            yum -y install httpd
            systemctl start httpd.service
            systemctl enable httpd.service
            echo "hello..using CloudFormation and UserData" > /var/www/html//index.html
      KeyName: "my-key-pair"
      SecurityGroupIds:
        - !Ref ApacheSecurityGroup

  ApacheSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "My Apache Security Group" 
        GroupName: "ApacheGroup"
        VpcId: vpc-127d8479
        SecurityGroupIngress:
          
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80

        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 443
          ToPort: 443

        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
        
        
          